version: '3.9'

services:
  backend-dev:
    image: django-api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/appuser/app/api
    environment:
      - PORT=8000
    env_file:
      - .env
    ports:
      - 8000:8000
    stdin_open: true

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5435:5432
    environment:
      - POSTGRES_NAME=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_HOST=${SQL_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: