name: Build and deploy to Heroku

on:
  workflow_dispatch:

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Heroku container registry login
      run: |
        echo ${{ env.HEROKU_API_KEY }} | docker login --username=_ registry.heroku.com --password-stdin

    - name: Image name
      id: image-name
      run: echo "IMAGE_NAME=registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web" >> "$GITHUB_OUTPUT"
      
    - name: Build Docker image
      run: |
        docker build . -t "${{ steps.image-name.outputs.IMAGE_NAME }}:latest"

    - name: Publish to container registry
      run: |
        docker push ${{ steps.image-name.outputs.IMAGE_NAME }} --all-tags

    - name: Release container
      run: |
        heroku container:release web --app ${{ env.HEROKU_APP_NAME }}
